In [239]:
"""ESTE ARCHIVO ES DE PRÁCTICA, NO EL ARCHIVO DE LA TAREA"""

'ESTE ARCHIVO ES DE PRÁCTICA, NO EL ARCHIVO DE LA TAREA'

In [240]:
import random
import numpy as np
import pandas as pd

In [241]:
# Función del Gradiente Descendente Vectorizada
def Gradiente_Vectorizada(Matriz_X, Y, alpha, iteraciones):
  n = np.shape(Matriz_X)
  p = np.shape(n)
  if p[0]==1:
    n = 1
  else:
    n = n[1]
  # Generar números aleatorios para las thetas dependiendo de la cantidad de variables en X
  thetas = random.sample(range(0,20), n+1)

  # Añadir columna de 1's a la matriz X
  unos = np.ones(len(y))
  X = np.vstack([unos, Matriz_X.T])
  X = X.T

  for m in range(iteraciones):
    # Multiplicar X.0
    X_0 = X @ thetas
    # Restar X.0 - Y
    h_Y = X_0 - Y.T
    # Multiplicar (X.0 - Y) * X.T
    j_0 = X.T @ h_Y
    # Multiplicar alpha/m * j_0
    mult = (alpha/len(y)) * j_0
    # Restar a thetas - mult
    thetas = thetas - mult
  return thetas

In [242]:
# Función para normalizar los datos, aplicando la fórmula de estandarización general
def Estandarizacion(DF):
  n = DF.shape
  columnas = n[1]
  num_ele = len(DF.iloc[:,0])
  DF_new = DF

  # Ciclo for para estandarizar por columna
  for m in range(columnas):
    mean = sum(DF.iloc[:,m])/num_ele
    std_dev = np.sqrt((sum((DF.iloc[:,m]-mean)**2)/num_ele))
    x_new = (DF.iloc[:,m] - mean)/std_dev
    DF.iloc[:,m] = x_new

  return DF


In [243]:
x = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
y = [1, 3, 6]
x = np.array(x)
y = np.array(y)
print(x)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [244]:
df = np.vstack([x.T,y])
x = pd.DataFrame(x)
y = pd.DataFrame(y)
df = df.T
df

array([[1, 1, 1, 1],
       [2, 2, 2, 3],
       [3, 3, 3, 6]])

In [245]:
y.shape

(3, 1)

In [246]:
df = pd.DataFrame(df)
df

0  1  2  3
0  1  1  1  1
1  2  2  2  3
2  3  3  3  6

In [247]:
df = Estandarizacion(df)
df

0         1         2         3
0 -1.224745 -1.224745 -1.224745 -1.135550
1  0.000000  0.000000  0.000000 -0.162221
2  1.224745  1.224745  1.224745  1.297771

In [251]:
x_n = df.iloc[:,0:3]
y_n = df.iloc[:,3]
y_n

0   -1.135550
1   -0.162221
2    1.297771
Name: 3, dtype: float64

In [252]:
thetas_n = Gradiente_Vectorizada(x_n,y_n,0.0001,1000)
thetas_n

array([11.76282762,  6.58008852, 12.58008852,  2.58008852])